name: build-caddy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
            
    - name: Get Caddy base version
      id: base
      run: |
        docker pull caddy:2-alpine
        TAG=$(docker inspect caddy:2-alpine --format '{{index .RepoTags 0}}')
        VERSION=$(echo $TAG | sed 's/caddy://')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Set lowercase owner
      run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build image
      run: |
        docker build \
          -t ghcr.io/${ OWNER_LC }/caddy-security-cloudflare-cfkv:${{ steps.base.outputs.version }} \
          -t ghcr.io/${ OWNER_LC }/caddy-security-cloudflare-cfkv:2 \
          -t ghcr.io/${ OWNER_LC }/caddy-security-cloudflare-cfkv:latest \
          .

    - name: Push all tags
      run: |
        docker push ghcr.io/${ OWNER_LC }/caddy-security-cloudflare-cfkv --all-tags
        
